In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import pandas as pd


os.chdir('/content/drive/MyDrive/AI_ML_Project_dataset')


print(os.listdir())

['personality_dataset.csv']

In [5]:

df = pd.read_csv('personality_dataset.csv')


print("Loaded shape:", df.shape)
df.head()

Loaded shape: (2900, 8)

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert

In [7]:
# data types and missing values
print("\n Dataset Info")
df.info()

 Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Time_spent_Alone           2837 non-null   float64
 1   Stage_fear                 2827 non-null   object
 2   Social_event_attendance    2838 non-null   float64
 3   Going_outside              2834 non-null   float64
 4   Drained_after_socializing  2848 non-null   object
 5   Friends_circle_size        2823 non-null   float64
 6   Post_frequency             2835 non-null   float64
 7   Personality                2900 non-null   object
dtypes: float64(5), object(3)
memory usage: 181.4+ KB

In [8]:
df.select_dtypes(include=['object'])

     Stage_fear Drained_after_socializing Personality
0            No                        No   Extrovert
1           Yes                       Yes   Introvert
2           Yes                       Yes   Introvert
3            No                        No   Extrovert
4            No                        No   Extrovert
...         ...                       ...         ...
2895         No                        No   Extrovert
2896         No                        No   Extrovert
2897        Yes                       Yes   Introvert
2898        Yes                       Yes   Introvert
2899         No                        No   Extrovert

[2900 rows x 3 columns]

In [10]:
print(df.isnull().sum())

Time_spent_Alone             63
Stage_fear                   73
Social_event_attendance      62
Going_outside                66
Drained_after_socializing    52
Friends_circle_size          77
Post_frequency               65
Personality                   0
dtype: int64

In [11]:
## ENCODE TEXT TO NUMBERS FIRST

# Map Yes/No to 1/0 

binary_mapping = {'Yes': 1, 'No': 0}
df['Stage_fear'] = df['Stage_fear'].map(binary_mapping)
df['Drained_after_socializing'] = df['Drained_after_socializing'].map(binary_mapping)

In [12]:
# Mapping the Personality to 1/0
target_mapping = {'Extrovert': 1, 'Introvert': 0}
df['Personality'] = df['Personality'].map(target_mapping)

In [13]:
df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,0.0,4.0,6.0,0.0,13.0,5.0,1
1,9.0,1.0,0.0,0.0,1.0,0.0,3.0,0
2,9.0,1.0,1.0,2.0,1.0,5.0,2.0,0
3,0.0,0.0,6.0,7.0,0.0,14.0,8.0,1
4,3.0,0.0,9.0,4.0,0.0,8.0,5.0,1

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Time_spent_Alone           2837 non-null   float64
 1   Stage_fear                 2827 non-null   float64
 2   Social_event_attendance    2838 non-null   float64
 3   Going_outside              2834 non-null   float64
 4   Drained_after_socializing  2848 non-null   float64
 5   Friends_circle_size        2823 non-null   float64
 6   Post_frequency             2835 non-null   float64
 7   Personality                2900 non-null   int64
dtypes: float64(7), int64(1)
memory usage: 181.4 KB

In [15]:
df.isnull().sum()

Time_spent_Alone             63
Stage_fear                   73
Social_event_attendance      62
Going_outside                66
Drained_after_socializing    52
Friends_circle_size          77
Post_frequency               65
Personality                   0
dtype: int64

In [16]:
num_cols = ['Time_spent_Alone', 'Social_event_attendance', 'Going_outside', 'Friends_circle_size', 'Post_frequency']
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# used the Median for continuous variables to protect data from being 
# skewed by extreme outliers.

In [17]:
binary_cols = ['Stage_fear', 'Drained_after_socializing']
for col in binary_cols:
    df[col] = df[col].fillna(df[col].mode()[0])


# used Mode for the binary categorical variables because they 
# represent discrete classes (Yes/No), and calculating an average or median
#  would result in invalid, fractional categories.

In [ ]:
# check for null values gain after fillna
df.isnull().sum()

Time_spent_Alone             0
Stage_fear                   0
Social_event_attendance      0
Going_outside                0
Drained_after_socializing    0
Friends_circle_size          0
Post_frequency               0
Personality                  0
dtype: int64

In [19]:
df.to_csv('dataset_cleaned.csv', index=False)